import type { SourceMetadata } from './types'

// TODO: official 曾用 disable: 'cf' 表达运行时差异；本期目录只描述业务可用性。
// 未来恢复多 runtime 时在这里引入显式 capability model，不能恢复魔法字符串。
export const sourceCatalog = {
  v2ex: {
    name: 'V2EX',
    column: 'tech',
    home: 'https://v2ex.com/',
    color: 'slate',
    interval: 600000,
    title: '最新分享',
    redirect: 'v2ex-share',
  },
  'v2ex-share': {
    name: 'V2EX',
    column: 'tech',
    home: 'https://v2ex.com/',
    color: 'slate',
    interval: 600000,
    title: '最新分享',
  },
  github: {
    name: 'Github',
    column: 'tech',
    home: 'https://github.com/',
    color: 'gray',
    interval: 600000,
    title: 'Today',
    type: 'hottest',
    redirect: 'github-trending-today',
  },
  'github-trending-today': {
    name: 'Github',
    column: 'tech',
    home: 'https://github.com/',
    color: 'gray',
    interval: 600000,
    title: 'Today',
    type: 'hottest',
  },
  hackernews: {
    name: 'Hacker News',
    column: 'tech',
    home: 'https://news.ycombinator.com/',
    color: 'orange',
    interval: 600000,
    type: 'hottest',
  },
  producthunt: {
    name: 'Product Hunt',
    column: 'tech',
    home: 'https://www.producthunt.com/',
    color: 'red',
    interval: 600000,
    type: 'hottest',
  },
  zhihu: {
    name: '知乎',
    column: 'china',
    home: 'https://www.zhihu.com',
    color: 'blue',
    interval: 600000,
    type: 'hottest',
  },
  weibo: {
    name: '微博',
    column: 'china',
    home: 'https://weibo.com',
    color: 'red',
    interval: 120000,
    title: '实时热搜',
    type: 'hottest',
  },
  bilibili: {
    name: '哔哩哔哩',
    column: 'china',
    home: 'https://www.bilibili.com',
    color: 'blue',
    interval: 600000,
    title: '热搜',
    type: 'hottest',
    redirect: 'bilibili-hot-search',
  },
  'bilibili-hot-search': {
    name: '哔哩哔哩',
    column: 'china',
    home: 'https://www.bilibili.com',
    color: 'blue',
    interval: 600000,
    title: '热搜',
    type: 'hottest',
  },
  baidu: {
    name: '百度热搜',
    column: 'china',
    home: 'https://www.baidu.com',
    color: 'blue',
    interval: 600000,
    type: 'hottest',
  },
  toutiao: {
    name: '今日头条',
    column: 'china',
    home: 'https://www.toutiao.com',
    color: 'red',
    interval: 600000,
    type: 'hottest',
  },
  ithome: {
    name: 'IT之家',
    column: 'tech',
    home: 'https://www.ithome.com',
    color: 'red',
    interval: 600000,
    type: 'realtime',
  },
  juejin: {
    name: '稀土掘金',
    column: 'tech',
    home: 'https://juejin.cn',
    color: 'blue',
    interval: 600000,
    type: 'hottest',
  },
  sspai: {
    name: '少数派',
    column: 'tech',
    home: 'https://sspai.com',
    color: 'red',
    interval: 600000,
    type: 'hottest',
  },
  coolapk: {
    name: '酷安',
    column: 'tech',
    home: 'https://coolapk.com',
    color: 'green',
    interval: 600000,
    title: '今日最热',
    type: 'hottest',
  },
  '36kr': {
    name: '36氪',
    column: 'tech',
    home: 'https://36kr.com',
    color: 'blue',
    interval: 600000,
    title: '快讯',
    type: 'realtime',
    redirect: '36kr-quick',
  },
  '36kr-quick': {
    name: '36氪',
    column: 'tech',
    home: 'https://36kr.com',
    color: 'blue',
    interval: 600000,
    title: '快讯',
    type: 'realtime',
  },
  '36kr-renqi': {
    name: '36氪',
    column: 'tech',
    home: 'https://36kr.com',
    color: 'blue',
    interval: 600000,
    title: '人气榜',
    type: 'hottest',
  },
  wallstreetcn: {
    name: '华尔街见闻',
    column: 'finance',
    home: 'https://wallstreetcn.com/',
    color: 'blue',
    interval: 300000,
    title: '快讯',
    type: 'realtime',
    redirect: 'wallstreetcn-quick',
  },
  'wallstreetcn-quick': {
    name: '华尔街见闻',
    column: 'finance',
    home: 'https://wallstreetcn.com/',
    color: 'blue',
    interval: 300000,
    title: '快讯',
    type: 'realtime',
  },
  cls: {
    name: '财联社',
    column: 'finance',
    home: 'https://www.cls.cn',
    color: 'red',
    interval: 300000,
    title: '电报',
    type: 'realtime',
    redirect: 'cls-telegraph',
  },
  'cls-telegraph': {
    name: '财联社',
    column: 'finance',
    home: 'https://www.cls.cn',
    color: 'red',
    interval: 300000,
    title: '电报',
    type: 'realtime',
  },
  jin10: {
    name: '金十数据',
    column: 'finance',
    home: 'https://www.jin10.com',
    color: 'blue',
    interval: 600000,
    type: 'realtime',
  },
  xueqiu: {
    name: '雪球',
    column: 'finance',
    home: 'https://xueqiu.com',
    color: 'blue',
    interval: 120000,
    title: '热门股票',
    type: 'hottest',
    redirect: 'xueqiu-hotstock',
  },
  'xueqiu-hotstock': {
    name: '雪球',
    column: 'finance',
    home: 'https://xueqiu.com',
    color: 'blue',
    interval: 120000,
    title: '热门股票',
    type: 'hottest',
  },
  steam: {
    name: 'Steam',
    column: 'world',
    home: 'https://store.steampowered.com',
    color: 'blue',
    interval: 600000,
    title: '在线人数',
    type: 'hottest',
  },
  douban: {
    name: '豆瓣',
    column: 'china',
    home: 'https://www.douban.com',
    color: 'green',
    interval: 600000,
    title: '热门电影',
    type: 'hottest',
  },
} as const satisfies Record<string, SourceMetadata>

export type SourceID = keyof typeof sourceCatalog
